name: Build on Release
on:
  release:
    types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Java 24
          uses: actions/setup-java@v2
          with:
            java-version: '24'
            distribution: 'temurin'
        - name: Build with Gradle
          run: |
            chmod +x gradlew
            ./gradlew shadowJar
        - name: Update release with JAR
          uses: softprops/action-gh-release@v1
          with:
            files: app/build/libs/app-all.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
